version: "3.8"

x-django: &django
  image: registry-vpc.cn-hangzhou.aliyuncs.com/ziqiang_studio/{{cookiecutter.project_name}}:django
  env_file: ./.env # ENV file
  depends_on:
    - redis
  networks:
    - app-net

services:
  ### Caddy container #########################################
  caddy:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/ziqiang_studio/caddy:latest
    container_name: {{cookiecutter.project_name}}-caddy
    depends_on:
      - django
    networks:
      - app-net
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.template.rule: Host(`api.{{cookiecutter.project_name}}.ziqiang.net.cn`)
      traefik.http.routers.template.entrypoints: websecure
      traefik.http.services.template.loadbalancer.server.port: 80

  ### Redis container ##########################################
  redis:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/ziqiang_studio/redis:latest
    container_name: {{cookiecutter.project_name}}-redis
    networks:
      - app-net

  ### Django container #########################################
  django:
    <<: *django
    container_name: {{cookiecutter.project_name}}-django
    volumes:
      - ./log:/app/logs:rw
{%- if cookiecutter.use_celery == 'y' %}

  ### Celery container ########################################
  celeryworker:
    <<: *django
    container_name: {{cookiecutter.project_name}}-celeryworker
    entrypoint: ./start-celeryworker.sh
    healthcheck:
      disable: true

  celerybeat:
    <<: *django
    container_name: {{cookiecutter.project_name}}-celerybeat
    entrypoint: ./start-celerybeat.sh
    healthcheck:
      disable: true

  flower:
    <<: *django
    container_name: {{cookiecutter.project_name}}-flower
    entrypoint: ./start-flower.sh
    healthcheck:
      disable: true
    expose:
      - 5555
{%- endif %}
{%- if cookiecutter.use_meilisearch == 'y' %}

  ### Celery container ########################################
  meili:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/ziqiang_studio/meilisearch:v1.0.2
    container_name: {{cookiecutter.project_name}}-meilisearch
    networks:
      - app-net
    env_file:
      - ./.env
    volumes:
      - ./meili_data:/meili_data
{%- endif %}

### Add Network Bridge info #########################################
networks:
  app-net: {}
  traefik:
    external: true
